### ISSUE TITLE
Future collections management systems scoping

### ISSUE THREAD

**Issue by jcateswellcome** [wellcomecollection/platform#5745] opened 2024-05-15 09:10 UTC
https://www.notion.so/wellcometrust/Future-collections-management-systems-scoping-80a72d2d6afd4995932ff8ea00cc468b?pvs=4

**Comment by jcateswellcome** [comment] 2024-10-02 09:24
For Q1 24/25 use the focus will be to review CMS/LMS in the running from an integration perspective

**Comment by kenoir** [comment] 2024-10-02 15:33
Dupe of https://github.com/wellcomecollection/platform/issues/5786

**Closed by kenoir** 2024-10-02 15:33 UTC
Labels: epic, Q4 2023/24, Q1 2024/25
