### ISSUE TITLE
Redirect Library Encore URLs

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5056] opened 2021-02-25 11:00 UTC
Redirect Encore URLs to https://wellcomecollection.org/works/{work_id}

Example URLs:

https://search.wellcomelibrary.org/iii/encore/search?target=erythromelalgia&submit=Search
https://search.wellcomelibrary.org/iii/encore/search/C__Srosalind%20paget
https://search.wellcomelibrary.org/iii/encore/record/C__Rb2475299
https://search.wellcomelibrary.org/iii/encore/record/C__Rb3185463?lang=eng
https://search.wellcomelibrary.org/iii/encore/record/C__Rb3153458__Sdrugscope__P0%2C1__Orightresult__U__X7?lang=eng&suite=cobalt

- [x] Redirect URLs in stage
- [ ] Redirect URLs in prod

**Comment by kenoir** [comment] 2021-02-25 11:53
Link to feature: https://wellcomecollection.productboard.com/feature-board/2024994-current-quarter-by-hierarchy/features/6699470/detail

**Comment by alexwlchan** [comment] 2022-01-11 10:49
I've written a basic set of redirects for the account, record, and search pages. You can see some examples of the expected redirects in this spreadsheet: https://github.com/wellcomecollection/platform/issues/5056 (this is used for the live testing)

I've only done a basic set of redirects for searches, based on the free-text search terms. Although Encore embeds more detailed search parameters (e.g. format, genre) in the URLs, I've not written logic to redirect those. I reckon they're pretty uncommon, and there are more important things for us to do.

These redirects are configured and deployed in stage. It's a fairly simple switch to enable them in prod, but we won't do that until we're ready to flip over properly.

If you want to test the redirects, create a bookmarklet with the following JavaScript (using https://mrcoles.com/bookmarklet/):

```javascript
if (document.location.href.startsWith('https://search.wellcomelibrary.org')) {
  document.location = document.location.href.replace(
    'search.wellcomelibrary.org',
    'search.stage.wellcomelibrary.org'
  );
} else {
  alert("This isn't an Encore URL!");
};
```

If you open a page in prod Encore and run the bookmarklet, it'll show you where that page will redirect when we enable redirections in prod.

**Comment by alexwlchan** [comment] 2022-01-11 10:49
I'm going to move this back to the TODO column until we're ready to enable this in prod, because I don't think there's any other work to do for now.

**Comment by alexwlchan** [comment] 2022-03-25 10:18
Closing as a duplicate of #5405.

**Closed by alexwlchan** 2022-03-25 10:18 UTC
Labels: :world_map: Wellcome Library Redirection
