### ISSUE TITLE
Improve search quality

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/platform#4625] opened 2020-07-08 08:26 UTC
### Objective
Researchers find more of what they're looking for

### Measures
- are we running regular tests?
- can users narrow down search results?
- are users finding more of what they're looking for?

### Initiatives

- [ ]

**Comment by jtweed** [comment] 2020-07-10 14:18
Dupe of #4642 4642

**Closed by jtweed** 2020-07-10 14:18 UTC
Labels: ⭐ Key Result
