### ISSUE TITLE
Issues signing in on stage after changing password on live

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5329] opened 2021-10-07 22:00 UTC
There's something slightly strange going on with signing into the stage Auth0 tenant as a library member.

Here's what I saw:

* Account on stage, able to log in fine
* Changed password on live, couldn't log in on stage with new password
* Deleted Auth0 account on stage, still couldn't log in with new password

So now I'm unable to log in on stage, even when there is no account in Auth0 for my patron record. I get told the user/password is wrong and a new Auth0 user is not created.

I'm likely doing something unexpected or wrong here, but I think it's worth a bit of investigation in case there is something slightly awry that might hit users who change their password after we go live.

I think @cbowskill saw this recently too.

**Comment by alexwlchan** [comment] 2022-01-05 12:02
I'm going to close this, as I reckon it was probably caused by our old approach to Auth0/Sierra account sync. We can open a new ticket if we see the issue again.

**Closed by alexwlchan** 2022-01-05 12:02 UTC
Labels: 🐛 Bug, :bookmark: Requesting
