### ISSUE TITLE
Full library catalogue data

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/platform#4626] opened 2020-07-08 08:32 UTC
### Objective
Researchers find more of what they're looking for

### Measures

- Are all required fields fully implemented?
- Do we support bib and series linking?
- Do we surface journals and electronic resources?
- Can users search across all Sierra bibliographic data?

### Initiatives

- [ ]

**Comment by jtweed** [comment] 2020-07-10 14:21
Dupe of #4643

**Closed by jtweed** 2020-07-10 14:21 UTC
Labels: ⭐ Key Result
