### ISSUE TITLE
Videos issues on https://wellcomecollection.org/works/

### ISSUE THREAD

**Issue by HarkiranDhindsa** [wellcomecollection/platform#4290] opened 2020-02-25 09:51 UTC
@jtweed 
**Issues noted on spot checking video titles on https://wellcomecollection.org/works/**

1) Mapping of video Sierra records to the API  https://wellcomecollection.org/works/   

AV titles have always had a separate e-bib record for the digitised file.
Example 1: Cruel Kindness
A search in wellcomelibrary.org will return 3 records for this title.
i) The film reel: https://search.wellcomelibrary.org/iii/encore/record/C__Rb1656590__Scruel%20kindness__Orightresult__X7?lang=eng&suite=cobalt

ii) Any physical video formats (in this case DVDs and Digibetas): https://search.wellcomelibrary.org/iii/encore/record/C__Rb1658712__Scruel%20kindness__P0%2C1__Orightresult__X7?lang=eng&suite=cobalt

iii) E-bib record for digitised item: https://search.wellcomelibrary.org/iii/encore/record/C__Rb1667616__Scruel%20kindness__P0%2C2__Orightresult__X7?lang=eng&suite=cobalt
We use the e-bib record to capture the license information in the 540 field for the digitised title (in this case CC BY NC)

However, on https://wellcomecollection.org/works, the search returns 2 records:
i) The film reel.  This is as it should be.
ii) A result for video. This shows the digitised file, but associated record has been pulled from the Sierra record for the physical format: https://wellcomecollection.org/works/mgsp56ab

The anomaly was first noticed when I changed the license in the Sierra e-bib for another title Sir Henry Dale and couldn’t see it update on Works. 

2) ‘View the item’ option
The ‘view the item’ button currently appears with all videos on Works, even if we are not planning to make the title available online, e.g. Nystagmus in epilepsy https://wellcomecollection.org/works/ckkcfmt9
The above title has been digitised but is a restricted item due to data protection of clinical content: https://wellcomelibrary.org/item/b30467883#?c=0&m=0&s=0&cv=0  The e-bib record is suppressed and hence does not appear on wellcomelibrary.org
The Works API  has pulled the record for the physical video format: https://wellcomecollection.org/works/ckkcfmt9 This allows you to click on the ‘View the item’ button, which takes you to the message’ 'We are working to make this item available online. But, in fact, we won’t be making this item available online. 

A similar issue arises for videos which have not yet been digitised, e.g. The Russian Arm https://wellcomecollection.org/works/w72fw4n5 Again, there is a ‘View the item’ button linked to the record of the physical video asset, but it may be years before a title is digitised.

**Comment by jtweed** [comment] 2020-11-13 17:59
Hi @HarkiranDhindsa. We're going to fix this in the short term by not merging AV works. That's covered by #4876, so I'm going to close this ticket and we can track there.

Longer term, we'll work with Collection Information on how they intend to catalogue AV going forward, which will have to change not least because some of the high-res digitisation material will become the master format.

When we know that, we'll work out how best to merge or otherwise group AV. In the meantime, there will be a work for each format like there is in Encore.

**Comment by alexwlchan** [comment] 2021-01-14 10:21
This is now fixed; searching for "Cruel kindness" on /works turns up three records, which is the desired behaviour AIUI: https://wellcomecollection.org/works?page=1&query=Cruel%20Kindness

**Comment by HarkiranDhindsa** [comment] 2021-01-14 11:15
Thanks, good to see the the separate records. 
But the video records seems to be linked the wrong way round. b16676166 should be the e-bib for the digitised item with the online link. b16587121 should be the catalogue record for the physical video formats.
For comparison, this is how they appear on Wellcome Library: https://search.wellcomelibrary.org/iii/encore/search/C__Scruel%20kindness__Orightresult__U?lang=eng  The e-bib is much more detailed with info for the segments of film.

**Comment by alexwlchan** [comment] 2021-01-14 11:50
I'm not quite sure how we could have got the two flipped round; reopening until we can investigate further.

**Comment by alexwlchan** [comment] 2021-03-15 10:12
I put in some fixes for this on Friday, and Harkiran has confirmed in Slack that this seems to be okay. I also can't see the unwanted "View item" button any more, so closing.

**Closed by alexwlchan** 2021-03-15 10:12 UTC
