### ISSUE TITLE
Stop hierarchies from displaying when they shouldn't

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/platform#5714] opened 2023-08-02 13:38 UTC
First reported on [27 July](https://wellcome.slack.com/archives/C8X9YKM5X/p1690460313094149):

> I've just realised that if you add a 773 to a Collection level record in Sierra it automatically creates a hierarchy: https://wellcomecollection.org/works/kd7vg53h. I thought it required reciprocal 774 fields, but clearly not - this is amazing thank you! cant tell you how much time/effort it could save
OH!!! it has literally just disappeared! But Nic saw it if you want verification!

And again on [2 August](https://wellcome.slack.com/archives/C8X9YKM5X/p1690979222109999):

> a phantom hierarchy is displaying again for this collection! https://wellcomecollection.org/works/kd7vg53h The records are using a MARC 773, which I understood acts as a series. Last week it listed all 500+ items, those vanished, now it is displaying a hierarchy for items that had their records edited yesterday, but not the rest of the collection. 
Rada Vlatkovic  is making them closed access. Is it just the system taking time to catch up with itself?

Possibly something to do with the order in which Sierra records are edited?

## Done when
- Hierarchies that shouldn't be displaying are not displaying

**Comment by paul-butcher** [comment] 2023-08-14 13:03
This is caused by the 773 at the top level.  This is making the root document behave like a branch.  Once it gets to the relation embedder, it can't tell the difference.  I have a candidate solution I can put in, but it can also be fixed in the data by not having that self-referential 77s.

**Comment by paul-butcher** [comment] 2023-09-04 11:09
Fixed and on main, pending a reindex.

**Closed** 2023-09-15 09:33 UTC
Labels: 📚Catalogue, platform-feedback
